#pragma once;

enum {
	E_ATTACK_TYPE_0,
	E_ATTACK_TYPE_1,
	E_ATTACK_TYPE_2,
	E_ATTACK_TYPE_3,
};

enum {
	E_MONSTER_TYPE_INVALID = -1,
	E_MONSTER_TYPE_0,
	E_MONSTER_TYPE_1,
	E_MONSTER_TYPE_2,
	E_MONSTER_TYPE_3,
};

enum {
	E_MONSTER_WAVE_TYPE_0,
	E_MONSTER_WAVE_TYPE_1,
	E_MONSTER_WAVE_TYPE_2,
	E_MONSTER_WAVE_TYPE_3,
};

enum {
	E_NODE_ID_INVALID = -1,
	E_NODE_ID_APP,
	E_NODE_ID_GAME_INFO,
	E_NODE_ID_HERO = 100,
	E_NODE_ID_TARGET = 500,
	E_NODE_ID_FLYER = 100000,
};
